"""
Writing a preset out as Hyprland configuration.

Hyprland is in the middle of moving from the classic .conf syntax to Lua, and
this machine already has a prepared hyprland.lua sitting next to its
hyprland.conf. When both exist the .lua wins and the .conf is ignored entirely,
so which file we generate is not a style choice — writing the wrong one means
the preset silently does nothing.

Hence the whole format question lives in this one module, behind two functions
(`target` and `render`). Migrating to Lua for good later means deleting a branch
here, not touching the animations section.

The Lua API, read off the Hyprland binary's own error strings and defaults:

    hl.curve("soft", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })
    hl.animation({ leaf = "windowsIn", enabled = true, speed = 5,
                   bezier = "soft", style = "popin 90%" })
    hl.config({ plugin = { dissolve = { block_size = 2 } } })

The classic equivalents:

    bezier = soft, 0.05, 0.9, 0.1, 1.0
    animation = windowsIn, 1, 5, soft, popin 90%
    plugin { dissolve { block_size = 2 } }
"""
from __future__ import annotations

from pathlib import Path

HYPR_DIR = Path.home() / ".config" / "hypr"
LUA_CONFIG = HYPR_DIR / "hyprland.lua"
CONF_CONFIG = HYPR_DIR / "hyprland.conf"

GENERATED_LUA = HYPR_DIR / "animations.lua"
GENERATED_CONF = HYPR_DIR / "animations.conf"

HEADER_LINES = [
    "Generated by rofi-hub — do not edit by hand.",
    "Every write replaces this file completely; change the preset instead:",
    "  data/presets/<id>.json in the rofi-launcher repository.",
]

# Settings that are protection rather than decoration. A preset must never be
# able to set them, and this module never writes them, so switching presets
# cannot resurrect a bug that was already fixed elsewhere in the config.
#
# key_leak_fix stops a held Escape from being handed to the window that gains
# focus — without it, closing rofi with Escape knocks Firefox out of fullscreen
# video.
PROTECTED_PLUGIN_KEYS = frozenset({"key_leak_fix", "key_leak_codes"})


def target():
    """Which file to generate, given how this machine's Hyprland is configured.

    Returns ("lua"|"conf", path). Lua wins whenever hyprland.lua exists, exactly
    as Hyprland itself decides.
    """
    if LUA_CONFIG.is_file():
        return "lua", GENERATED_LUA
    return "conf", GENERATED_CONF


def _fmt_number(value):
    """1.0 → "1", 0.35 → "0.35". Hyprland accepts both, but a trailing ".0"
    makes a diff against the hand-written original look like a change."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _clean_plugin(settings):
    return {k: v for k, v in (settings or {}).items() if k not in PROTECTED_PLUGIN_KEYS}


def _parse_animation(spec):
    """"1, 20, default, popin 100%" → (enabled, speed, curve, style)."""
    parts = [p.strip() for p in str(spec).split(",")]
    enabled = parts[0] not in ("0", "false", "")
    speed = parts[1] if len(parts) > 1 else "1"
    curve = parts[2] if len(parts) > 2 else "default"
    style = ", ".join(parts[3:]) if len(parts) > 3 else ""
    return enabled, speed, curve, style


def render_conf(preset):
    """The preset as classic hyprland.conf syntax."""
    out = [f"# {line}" for line in HEADER_LINES]
    out.append(f"# preset: {preset['id']}")
    out.append("")

    for name, points in (preset.get("beziers") or {}).items():
        numbers = ", ".join(_fmt_number(p) for p in points)
        out.append(f"bezier = {name}, {numbers}")
    if preset.get("beziers"):
        out.append("")

    out.append("animations {")
    out.append("    enabled = true")
    for leaf, spec in (preset.get("animations") or {}).items():
        out.append(f"    animation = {leaf}, {spec}")
    out.append("}")

    plugin = _clean_plugin(preset.get("dissolve"))
    if plugin:
        out.append("")
        out.append("plugin {")
        out.append("    dissolve {")
        for key, value in plugin.items():
            out.append(f"        {key} = {_fmt_number(value)}")
        out.append("    }")
        out.append("}")

    return "\n".join(out) + "\n"


def render_lua(preset):
    """The preset as a Lua chunk, meant to be pulled in with dofile()."""
    out = [f"-- {line}" for line in HEADER_LINES]
    out.append(f"-- preset: {preset['id']}")
    out.append("")

    for name, points in (preset.get("beziers") or {}).items():
        pairs = ", ".join(
            f"{{ {_fmt_number(points[i])}, {_fmt_number(points[i + 1])} }}"
            for i in (0, 2)
        )
        out.append(
            f'hl.curve("{name}", {{ type = "bezier", points = {{ {pairs} }} }})'
        )
    if preset.get("beziers"):
        out.append("")

    for leaf, spec in (preset.get("animations") or {}).items():
        enabled, speed, curve, style = _parse_animation(spec)
        fields = [
            f'leaf = "{leaf}"',
            f"enabled = {'true' if enabled else 'false'}",
            f"speed = {speed}",
            f'bezier = "{curve}"',
        ]
        if style:
            fields.append(f'style = "{style}"')
        out.append("hl.animation({ " + ", ".join(fields) + " })")

    plugin = _clean_plugin(preset.get("dissolve"))
    if plugin:
        out.append("")
        body = ", ".join(f"{k} = {_fmt_number(v)}" for k, v in plugin.items())
        out.append(f"hl.config({{ plugin = {{ dissolve = {{ {body} }} }} }})")

    return "\n".join(out) + "\n"


def render(preset, fmt=None):
    if fmt is None:
        fmt, _ = target()
    return render_lua(preset) if fmt == "lua" else render_conf(preset)


def write(preset):
    """Generate the configuration for this machine. Returns the active path.

    Both formats are written, not just the one in use. The migration to Lua is a
    single `mv` away on this machine, and the main config includes the generated
    file by name — so if only the active format existed, the moment the other
    config took over it would point at a file that was not there. Hyprland
    treats a Lua error as fatal enough to fall back to emergency keybinds, which
    is a bad way to find out. Generating both costs a few hundred bytes.
    """
    fmt, active = target()
    active.parent.mkdir(parents=True, exist_ok=True)
    for this_fmt, path in (("conf", GENERATED_CONF), ("lua", GENERATED_LUA)):
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(render(preset, this_fmt), encoding="utf-8")
        tmp.replace(path)
    return active


def include_line():
    """The line the main config needs so that the generated file is read."""
    fmt, path = target()
    if fmt == "lua":
        return f'dofile("{path}")'
    return f"source = {path}"


def is_included():
    """Whether the main config already pulls the generated file in."""
    fmt, path = target()
    main = LUA_CONFIG if fmt == "lua" else CONF_CONFIG
    try:
        text = main.read_text(encoding="utf-8")
    except OSError:
        return False
    return path.name in text
